FROM node:16

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o arquivo package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do projeto
COPY . .

# Exponha a porta em que o React rodará
# EXPOSE 3000

# Defina a porta 80 como padrão no ambiente
ENV PORT 80

# Comando padrão para iniciar o aplicativo
CMD ["npm", "start"]

# FROM node:18
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 3000
# CMD ["npm", "start"]
